### PR TITLE
Request for the MimoCAD creatorId.

### PR DESCRIPTION
**Pull request by Dygear**
Not sure if I'm doing this right. I do not have the USB VID, if that matters, for this requested creatorId. `4D43` = `MC` on the ASCII table.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Please pick an ID with the first two != 0. You could do 0x4d43_0000 for example.

**Comment by Dygear** [comment]
Fixed, sorry -- Misunderstood.

**Review by tannewt — CHANGES_REQUESTED** [review]
Please create a `0x4xxx_xxxx` header below and add it there.

**Comment by dhalbert** [comment]
@Dygear are you still working on this board or is the request now moot? Just cleaning up some open PR's. Thanks.

**Comment by Dygear** [comment]
I have two boards and I'd love to keep this alive for them. I actually have some help with a new hire taking the reins of that.

**Comment by Dygear** [comment]
You can close. Thank you.

**Pull request closed without merging**
